// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLXR8eriw04jNfG62in19LUNIsMoR31mM',
    appId: '1:386525484164:web:d8769531b7b5956e7dded1',
    messagingSenderId: '386525484164',
    projectId: 'indigenous-plants-app',
    authDomain: 'indigenous-plants-app.firebaseapp.com',
    storageBucket: 'indigenous-plants-app.appspot.com',
    measurementId: 'G-VCX211W1LB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKkdC3Ny8DUSG5pMxkgeUsc2Zs1bGm4U8',
    appId: '1:386525484164:android:04d2c126743989107dded1',
    messagingSenderId: '386525484164',
    projectId: 'indigenous-plants-app',
    storageBucket: 'indigenous-plants-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu9WGKkzOmDNw9P0HG6ME67FVncD9vTmM',
    appId: '1:386525484164:ios:d6959d16533e89547dded1',
    messagingSenderId: '386525484164',
    projectId: 'indigenous-plants-app',
    storageBucket: 'indigenous-plants-app.appspot.com',
    iosBundleId: 'com.example.indigenousPlant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAu9WGKkzOmDNw9P0HG6ME67FVncD9vTmM',
    appId: '1:386525484164:ios:670b35b9ee61497a7dded1',
    messagingSenderId: '386525484164',
    projectId: 'indigenous-plants-app',
    storageBucket: 'indigenous-plants-app.appspot.com',
    iosBundleId: 'com.example.indigenousPlant.RunnerTests',
  );
}
