// {
//   "welcome": "Káàbọ̀",
//   "to_the": "sí",
//   "welcome_desc": "Ilé àwọn ewèko",
//   "plant_u_might_love": "Àwọn èwe tí a ṣàbẹ̀wò",
//   "intro": "Àyè kan níbi tí o le kọ́ nípa àwọn èwe ibílẹ̀",
//   "look_for_plant": "Wa fun ọgbin",
//   "plant_category": "Ẹka ohun ọgbìn",
//   "find_your_plant": "Wa ọgbin rẹ",
//   "plant_name": "",
//   "description": "Isapejuwe",
//   "economic_value": "Iye ọrọ aje",
//   "local_value": "Oogun iye",
//   "habitat": "Ibugbe",
//   "vegetables": "Ẹfọ",
//   "tubers": "isu",
//   "crops": "Ere-oko",
//   "seeds": "Irugbin",
//   "fruits": "eso",
//   "leaves": "ewe",
//   "suggested_first_plant": "Ilá",
//   "suggested_second_plant": "Ewe",
//   "suggested_third_plant": "Ewa ara ilu Afirika",
//   "suggested_fourth_plant": "Apple Star Star Apple"
// }