// {
//   "welcome": "Káàbọ̀",
//   "to_the": " sí ",
//   "welcome_desc": "Ilé àwọn Ohun Ọ̀gbìn",
//   "plant_u_might_love": "Ohun Ọ̀gbìn tí o lè ní fẹ́sí",
//   "intro": "ibi tí o lè kọ ẹ̀kọ́ nípa àwọn irúgbìn",
//   "look_for_plant": "Wa fun ọgbin",
//   "plant_category": "Ẹka ohun Ọ̀gbìn",
//   "find_your_plant": "Wa ọgbin rẹ",
//   "plant_name": "Orúkọ ohun Ọ̀gbìn",
//   "description": "Ìsàpèjúwe",
//   "economic_value": "Iyè Ọrọ̀ ajé",
//   "local_value": "Òògùn Iyè",
//   "habitat": "Ibùgbé",
//   "vegetables": "Ẹ̀fọ́",
//   "tubers": "Isu",
//   "seeds": "irúgbìn",
//   "fruits": "èso",
//   "leaves": "ewé",
//   "suggested_first_plant": " Ilá",
//   "suggested_second_plant": "Ewúro",
//   "suggested_third_plant": "Irú",
//   "suggested_fourth_plant": "Agbálùmọ̀",
//   "fluted_Pumpkin": "Ẹ̀fọ́ Úgù",
//   "wild_Lettuce": "Ẹ̀fọ́ yáńri",
//   "scent_Leaf": "Efirin",
//   "bitter_Leaf": "Ewé",
//   "okro": "Ilá",
//   "okro_economic_value":"Ilá  ní ọlọ́rọ̀ ní àwọn vitamin àti eroja, tó jẹ́ apá tó ṣeé ṣe àyẹ̀wò nínú àwọn oúnjẹ ní gbogbo agbègbè, Pẹ̀lú náà, ẹ̀kórò ní àwọn ìlò nínú ìṣòwò, pẹ̀lú ìlò rẹ̀ nínú àwọn oúnjẹ tí a ṣe àti bí ohun èlò ìkòkò ní àwọn ìṣòwò tó yàtọ̀.",
//   "okro_local_value": "Ó jẹ́ ẹ̀fọ́ pataki nínú àwọn oúnjẹ àdúgbò, tí ó ń ṣe ìmúlẹ̀ ìtọ́jú oúnjẹ àti àtọ́runwá. Yàtọ̀ sí pé ó jẹ́ eroja pàtàkì nínú àwọn àdídá ìṣe tó dájú bíi gumbo àti ẹ̀kuru, ẹ̀kórò ń ṣe àǹfààní sí àwọn ìṣòwò àdúgbò nípa ìṣèjọba rẹ̀ àti títà rẹ̀ ní àwọn ọjà. ",
//   "okro_habitat": "Òjò gbòòrò: Ilá fẹ́ràn ibi tí ó gbona, tí ó sì ní òjò gbòòrò. Ó dára jùlọ nígbà tí ìgbà òtútù kò sí. Òjò tó dara fún Ilá ní láàrin 75°F àti 95°F (24°C sí 35°C).Aìkọ̀tútù: Ilá kì í fẹ́ ibi tí òtútù máa ń wà. Ilá máa ń gbòòrò nínú ibi tí ìgbà gbígbóná rẹ̀ pẹ́.Ìmọ̀lẹ̀ òrùn púpọ̀: Ilá fẹ́ràn ìmọ̀lẹ̀ òrùn fún wakati mẹ̀fà sí mẹ̀jọ (6-8) ní ọjọ́ kan. Ìmọ̀lẹ̀ òrùn tí ó tó kì í ṣe pàtàkì fún igbó àwọn àtẹgùn Ilá.",
//   "okro_desc": " Ilá ni igi tí ó jẹ́ ọmọ ẹ̀gbẹ́ irúgbìn, tí a tún mọ̀ sí igi tí ó ń mú èsò kan tí a ń pè ní Ilá. Ní Yorùbá, a tún lè pè ní Ilá. Ilá jẹ́ èsò kan tí ó dùn mọ́ oúnjẹ nígbà púpọ̀, pàápàá jùlọ ní ilé Yorùbá. Igi Ilá ń dàgbà gà tó tó ẹ̀wọ̀n méta sí ẹ̀wọ̀n márùn-ún. Ó ní ewé aláwò ewé tó dàbí irún. Èsò Ilá náà jẹ́ kékeré, ó sì ní irún kékeré lórí rẹ̀. Nígbà tí a bá gé Ilá sílẹ̀, a máa ń rí irún wọ̀nyí.Nígbà tí a bá dáná Ilá, ó máa ń tú ìtò kan jáde tí ó ń ràn ìdáná lọ́wọ́ láti sọ àwọn oúnjẹ pọ̀. Èyí mú kí Ilá jẹ́ èròjà pàtàkì fún obè, pàápàá jùlọ fún obè Ilá. Obè Ilá jẹ́ irú obè kan tí a máa ń ṣe pẹ̀lú Ilá àti ewúrẹ́, adìẹ, tàbí ẹran mìíràn.Ilá tún ní oríṣiríṣi ìwòsàn lárà rẹ̀. Ó ní vitamin C, àti oríṣiríṣi ohun alumọ̀ni tí ó jẹ́ kí ó dára fún ara àti ètò ìdábòbò ara. A máa ń lo Ilá fún ìtójú arùn bí eèbì, ìtò súgà, àti ìṣòro inú.Gbogbo èyí jẹ́ ìdí tí Ilá fí jẹ́ èsò pàtàkì láàrín Yorùbá, tí a sì máa ń tọ́jú rẹ̀ dáadáa nínú ọ̀kọ wa.",
//   "african_Spinach": "Bunkun ti Afirika Hibiscus (Roselle)",
//   "hibiscus_leaf": "",
//   "jute": "Ewédú",
//   "jute_desc": "Ewédú ni ọlọ́rọ̀ ní àwọn fítámì àti Èròjà, ó ràn l’ọ́wọ́ ní dídáwọ̀n jíjẹ, ṣíṣe ojú dára, àti ìfàgílè ààbò. Se ẹ̀wẹ́ náà bí ewédú, máa jẹ.",
//   "jute_economic_value": "Ta ni awọn ọja ati lo niya ni onje agbegbe.",
//   "jute_local_value": "Ti a mọ fun akoonu okun giga rẹ ati lo lati mura satelaiti ewhedu olokiki, eyiti o gbagbọ lati ṣe iranlọwọ jẹ tito nkan lẹsẹsẹ ati pese awọn vitamin ati awọn ohun alumọni pataki.",
//   "jute_habitat": "Gbooro daradara ni awọn oju-aye olooru, nigbagbogbo ri ninu awọn ọgba ati awọn oko.",
//   "pumpkinLeaves": "Ewébẹ̀",
//   "pumpkin_desc": "Gbooro, alawọ ewe alawọ ewe lati igi elegede ti a fi omi ṣan",
//   "pumpkin_economic_value": "Ni idiyele pupọ ni ọja fun awọn anfani ijẹẹmu rẹ ati awọn lilo ọmu.",
//   "pumpkin_local_value": "Ọlọrọ ninu irin ati vitamin, lo lati ṣe alekun awọn ipele ẹjẹ, ati ni ọpọlọpọ awọnmo ati awọn stes.",
//   "pumpkin_habitat": "Fesi ni awọn ọgba ati awọn oko jakejado awọn ẹkun okun tropical.",
//   "waterleaf": "Ẹ̀fọ́ Gúre",
//   "waterleaf_desc": "Ewebe alawọ ewe succulent ti o sin ni awọn agbegbe tutu.",
//   "waterleaf_econo": "A ti lo wọpọ ni awọn ọja ati lo ninu awọn ounjẹ oriṣiriṣi",
//   "waterleaf_local": "Ọlọrọ ninu irin ati vitamin, lo lati ṣe alekun awọn ipele ẹjẹ, ati ni ọpọlọpọ awọnmo ati awọn stes.",
//   "waterleaf_habitat": "Fesi ni awọn ọgba ati awọn oko jakejado awọn ẹkun okun tropical.",
//   "yam": "iṣu",
//   "cassava": "Ẹ̀gẹ́",
//   "cassava_desc":"àwọn igi ẹ̀gẹ̀ jẹ́ gíga àti ìrùmọ̀, tí ó ní àwọn ìdí tí ó gùn. Ẹ̀ka rẹ̀ jẹ́ tan-brown àti lè kó tó ẹ̀gàn mẹ́wàá (3 mèta) ní gíga. Awọn ewé rẹ̀ jẹ́ ńlá, aláwọ̀ ewé, tí ó ní irísí iròyìn kìlọ̀ọ̀rọ̀ mẹ́ta tàbí mẹ́rèè, àti pé àwọn ewé yìí jẹ́ gígùn pẹ̀lú àwọn ipin tó yẹ̀ wá. Igi náà máa ń ṣèdá àwọn odò tó kéré, pẹ̀lú awọ̀ pẹ̀lú ẹ̀dá aláwọ̀ funfun tàbí yélò.\n Nígbà tí ẹ̀gẹ̀ bá ti pẹ̀, igi náà máa ń di ìgbẹ̀ àti gíga. Àwọn ewé le bẹ̀rẹ̀ sí ní yíyọ̀ sílẹ̀. Apá tí a ń jẹ, tí ó jẹ́ gbígbòná, wà ní ilẹ̀ àti dájú pé ó ní irísí àwọ̀-brown tí ó ní ẹ̀dá kìlọ̀. Nígbà tí o bá fa a sẹ́yìn, ọkà náà jẹ́ dúró àti funfun ní inú, ó lè pọ̀ tó ẹsẹ̀ kan (30 sentimita) tàbí ju bẹ́ẹ̀ lọ.",
//   "sweet_Potato": "Ọ̀dùnkún dùn",
//   "cocoyam": "Ẹ̀kọ́yàm",
//   "water_Yam": "Ọ̀jọ̀jọ̀",
//   "white_Yam": "Ewùrà",
//   "yellow_Yam": "Èsúúrú",
//   "taro": "kókò",
//   "aerial_Yam": "Erial lem"
// }